### ISSUE TITLE
Nice time breaks after the new year.

### ISSUE THREAD

**Issue by caseydierking** [pvledoux/blocks-nicetime#4]
I've been happily using your plugin on my website. However, I noticed it breaks after the new year. All blog entries times show up as on 20-12-2014 00:00.

Any thoughts on this?

**Comment by pvledoux** [comment]
Hi, actually Nice time is not really necessary with Craft, as you have the same functionality builtin with Twig: http://twig.sensiolabs.org/doc/filters/date_modify.html. I should probably deprecated this plugin.

Cheers.
